/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package shopscanmanager;

import com.michaelbaranov.microba.calendar.DatePicker;
import java.awt.Component;
import java.awt.Dimension;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Hashtable;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JPanel;

/**
 *
 * @author xkalibaer
 */
public class ReportsSettings extends javax.swing.JPanel {

    private Connection con;
    private DatePicker dp;
    private DatePicker dp1;
    private Mysql mysql;
    private Dimension dimension;
    private String installPath;
    private HomeScreen hs;
    private String fileSelected;
    int csv=0;
    int pdf=0;
    int xls=0;

    String location=installPath + "\\reports\\";

    int autogenerate=0;
    int autoUser=0;
    int autoItem=0;
    int autoSync=0;
    String generateWhen="";

    List restrictList;
    /**
     * Creates new form ReportsSettings
     */
    public ReportsSettings(Mysql mysql, Connection con, Dimension dimension, String installPath, HomeScreen hs) {
        this.con=con;
        this.mysql=mysql;
        this.dimension=dimension;
        this.installPath=installPath;
        this.hs=hs;
        initComponents();
        System.out.println("New User Reports");
    }

    
    public JPanel getAllComponents()
    {
        try 
        {
            PreparedStatement pr3;
            pr3 = this.con.prepareStatement("Select * from user_type");
            ResultSet rs1=this.mysql.query(pr3);
            ArrayList ar=new ArrayList();
            DefaultListModel dlm=new DefaultListModel();
            dlm.addElement("-Types of Users-");
            while (rs1.next()) { 
                System.out.println("User type=" + rs1.getString("usertype"));
                dlm.addElement(rs1.getString("usertype"));
            }
            this.jList1.setModel(dlm);
            location=installPath + "\\reports";
            this.jTextField1.setText(installPath + "\\reports");
            pr3 = this.con.prepareStatement("Select * from report_settings");
            rs1=this.mysql.query(pr3);
            while (rs1.next()) { 
                if(rs1.getString("reportPath").length()>0)
                {
                    this.jTextField1.setText(rs1.getString("reportPath").trim());
                }
                
                if(rs1.getInt("csv")==1){this.jCheckBox1.setSelected(true);}
                if(rs1.getInt("xls")==1){this.jCheckBox2.setSelected(true);}
                if(rs1.getInt("pdf")==1){this.jCheckBox3.setSelected(true);}
                
                if(rs1.getInt("autoYes")==1){this.jRadioButton1.setSelected(true);this.jRadioButton2.setSelected(false);}
                else{this.jRadioButton2.setSelected(true);this.jRadioButton1.setSelected(false);}
                
                if(rs1.getInt("autoUserReport")==1){this.jCheckBox4.setSelected(true);}
                if(rs1.getInt("autoItemReport")==1){this.jCheckBox5.setSelected(true);}
                if(rs1.getInt("autoSyncReport")==1){this.jCheckBox7.setSelected(true);}
                
                System.out.println("When ===" + rs1.getString("autoWhen"));
                if(rs1.getString("autoWhen").length()>0){this.jComboBox1.setSelectedItem(rs1.getString("autoWhen"));}
                if(rs1.getString("userRestrictions").length()>0)
                {
                    String[] us=rs1.getString("userRestrictions").split(", ");
                    for(int count1=0; count1<us.length; count1++)
                    {
                        System.out.println("Set this selected = " + us[count1]);
                        this.jList1.setSelectedValue(us[count1], true);
                        
                    }
                }
            }
            
            this.jComboBox1.removeAllItems();
            this.jComboBox1.addItem("Select One");
            this.jComboBox1.addItem("09:00");
            this.jComboBox1.addItem("12:00");
            this.jComboBox1.addItem("16:00");
            this.jComboBox1.addItem("18:00");
            
        } catch (SQLException ex) {
            Logger.getLogger(ReportsSettings.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        return this;
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jPanel2 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(23, 21, 21));

        jPanel1.setBackground(new java.awt.Color(23, 21, 21));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Generate these types of reports:");

        jCheckBox1.setBackground(new java.awt.Color(40, 40, 40));
        jCheckBox1.setForeground(new java.awt.Color(204, 204, 204));
        jCheckBox1.setText(".csv reports");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jCheckBox2.setBackground(new java.awt.Color(40, 40, 40));
        jCheckBox2.setForeground(new java.awt.Color(204, 204, 204));
        jCheckBox2.setText(".xsl reports");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });

        jCheckBox3.setBackground(new java.awt.Color(40, 40, 40));
        jCheckBox3.setForeground(new java.awt.Color(204, 204, 204));
        jCheckBox3.setText(".pdf reports");
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(160, 160, 160));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Save my reports to this folder:");

        jButton1.setBackground(new java.awt.Color(40, 40, 40));
        jButton1.setText("Open...");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jSeparator2.setBackground(new java.awt.Color(160, 160, 160));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Autogenerate Reports");

        jRadioButton1.setBackground(new java.awt.Color(40, 40, 40));
        jRadioButton1.setForeground(new java.awt.Color(204, 204, 204));
        jRadioButton1.setText("Yes");

        jRadioButton2.setBackground(new java.awt.Color(40, 40, 40));
        jRadioButton2.setForeground(new java.awt.Color(204, 204, 204));
        jRadioButton2.setText("No");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jSeparator3.setBackground(new java.awt.Color(160, 160, 160));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Limit report generation access to these types of users:");

        jCheckBox4.setBackground(new java.awt.Color(40, 40, 40));
        jCheckBox4.setForeground(new java.awt.Color(204, 204, 204));
        jCheckBox4.setText("User Reports");

        jCheckBox5.setBackground(new java.awt.Color(40, 40, 40));
        jCheckBox5.setForeground(new java.awt.Color(204, 204, 204));
        jCheckBox5.setText("Inventory Reports");
        jCheckBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox5ActionPerformed(evt);
            }
        });

        jCheckBox7.setBackground(new java.awt.Color(40, 40, 40));
        jCheckBox7.setForeground(new java.awt.Color(204, 204, 204));
        jCheckBox7.setText("Sync Reports");
        jCheckBox7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox7ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(40, 40, 40));
        jButton2.setText("Save Settings");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(40, 40, 40));
        jButton3.setText("Cancel");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jPanel2.setBackground(new java.awt.Color(26, 26, 26));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Generate Reports ");

        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("everyday at this time:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox1)
                            .addComponent(jCheckBox2)
                            .addComponent(jCheckBox3)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jRadioButton1)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRadioButton2))
                                    .addComponent(jCheckBox7)
                                    .addComponent(jCheckBox5)
                                    .addComponent(jCheckBox4))
                                .addGap(46, 46, 46)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(1218, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox3)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox7))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(1083, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1565, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1635, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jCheckBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox5ActionPerformed

    private void jCheckBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox7ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Hashtable h1=new Hashtable();
        try {
            // TODO add your handling code here:
            if(jCheckBox1.isSelected()){csv=1;}
            if(jCheckBox2.isSelected()){pdf=1;}
            if(jCheckBox3.isSelected()){xls=1;}
            
            if(jRadioButton1.isSelected()){
                autogenerate=1;
                generateWhen= jComboBox1.getSelectedItem().toString();
                
                if(jCheckBox4.isSelected()){autoUser=1;}
                if(jCheckBox5.isSelected()){autoItem=1;}
                if(jCheckBox7.isSelected()){autoSync=1;}
            }
            
            restrictList=jList1.getSelectedValuesList();
            String restrictListStr="";
            
            for(int count=0; count<restrictList.size(); count++)
            {
                restrictListStr=restrictListStr + "" + restrictList.get(count);
                if(count!=(restrictList.size() - 1))
                {
                    restrictListStr=restrictListStr + ", ";
                }
            }
            boolean proceed=false;
            if(autogenerate==1 && generateWhen.length()>0 && (!generateWhen.equals("Select One")))
            {
                proceed=true;
            }
            if(autogenerate==0)
            {
                proceed=true;
            }
            if(restrictListStr.length()>0 && proceed==true && location.length()>0)
            {
                PreparedStatement pr3 = this.con.prepareStatement("Select * from report_settings");
                ResultSet rs1=this.mysql.query(pr3);
                String sql="INSERT INTO report_settings (`csv`, `pdf`, `xls`, `reportPath`, `autoYes`, `autoWhen`, "
                        + "`autoUserReport`, `autoItemReport`, "
                        + "`autoSyncReport`, `userRestrictions`) VALUES(?,?,?,?,?,?,?,?,?,?)";
                while (rs1.next()) { 
                sql="UPDATE report_settings SET `csv` = ?, `pdf` = ?, `xls` = ?, "
                        + "`reportPath` = ?, `autoYes` = ?, `autoWhen` = ?, `autoUserReport` = ?, `autoItemReport` = ?, "
                        + "`autoSyncReport` = ?, `userRestrictions` = ? WHERE id = " + rs1.getString("id");
                }

                PreparedStatement pr=con.prepareStatement(sql);
                pr.setInt(1, csv);
                pr.setInt(2, pdf);
                pr.setInt(3, xls);
                pr.setString(4, location);
                pr.setInt(5, autogenerate);
                pr.setString(6, generateWhen);
                pr.setInt(7, autoUser);
                pr.setInt(8, autoItem);
                pr.setInt(9, autoSync);
                pr.setString(10, restrictListStr);

                System.out.println("SQL statement for report settings =");
                int shopItemCount = pr.executeUpdate();
                
                h1.put("success", true);
                h1.put("message", "Settings saved!");
            }
            else
            {
                
                h1.put("success", false);
                h1.put("message", "Settings not saved. \n"
                        + "If you select to autogenerate, select a \n"
                        + "time of the day to generate your report.\n"
                        + "Ensure you select the user levels that \n"
                        + "can only generate reports manually.\n"
                        + "Ensure you provide a folder to save your \n"
                        + "reports or select the default checkbox");
            }
        } catch (SQLException ex) {
            Logger.getLogger(ReportsSettings.class.getName()).log(Level.SEVERE, null, ex);
            
            h1.put("success", false);
            h1.put("message", "Settings not saved. Try again later");
        }
        this.hs.displayProcessMessage(h1);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            File file=new UtilUse().getDirectoryChoice((Component)evt.getSource(), new JFileChooser(),
                    new File(new UtilUse().GetMyDocuments()), "Select a folder location");
            this.fileSelected=file.getCanonicalPath();
            System.out.println("file selected = " + this.fileSelected);
            this.location=fileSelected;
            this.jTextField1.setText(fileSelected);
            //System.err.println(file.getAbsoluteFile() + " and " + file.getCanonicalPath() + " and " + file.getCanonicalFile());
        } catch (IOException ex) {
            new UtilUse().Log(ex);
            Logger.getLogger(Settings.class.getName()).log(Level.SEVERE, null, ex);
        }catch (Exception ex) {
            new UtilUse().Log(ex);
            Logger.getLogger(Settings.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
